services:
  web:
    build: .
    image: kevinfrederick/resumeapp_web:1.0
    container_name: web
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: resume123
      DB_NAME: resumeapp

  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: resume123
      MYSQL_DATABASE: resumeapp
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: